name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker pull $DOCKER_USER/ucidrugreview_flask_app:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f ucidrugreview_flask_app-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker run -it -d -p 8000:8000 --name ucidrugreview_flask_app-container $DOCKER_USER/ucidrugreview_flask_app:latest

